# build.zig.zon-sha256: 10106bec32060d1f43411244bd176a72854e18fd655a14d0ecf0c48fe97874b4
# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
  fetchgit,
}:
linkFarm "zig-packages" [
  {
    name = "wayland-0.7.0-dev-lQa1krn7AQCMUzT3J6gWyukl3L3kbMtCZy9djQemUYA-";
    path = fetchgit {
      url = "https://github.com/ifreund/zig-wayland";
      rev = "589aaf7c213159547d774ef8e6491f0045c511d5";
      hash = "sha256-C1KR8BhbzbO+9RC1ExIDmbKARnzK2XA3+0pzxL4K2Qw=";
    };
  }
  {
    name = "xkbcommon-0.5.0-dev-VDqIe0y2AgA1RzA2ICMdGhaAgSXdhtRTbYybQQu7WfOa";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-xkbcommon.git";
      rev = "6c2f41e269adde0d2cd58d20c02c4f8803d83eb1";
      hash = "sha256-vreObBYsAsb33qKdTpQGFqPbweidMw+L1MRWxqwq07E=";
    };
  }
  {
    name = "zigimg-0.1.0-8_eo2hgmGAAqEt2YcxP9GKGmYVdtLHEEBO03PZQ_3IgG";
    path = fetchgit {
      url = "https://github.com/zigimg/zigimg.git";
      rev = "575e194a494144aced6b7e920b13faab48864340";
      hash = "sha256-jlpVIAjw6Dqk+gOOb8nkLL2JGJsK6n7mGFxOtTudtyg=";
    };
  }
]
